name: Build Extension and create release

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{matrix.node-version}}
          
      - name: 3. Cache dependencies
        uses: actions/cache@master
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}
          
      - name: 4. Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: 
          yarn install

      - name: 5. Webpack build 
        run:
          yarn build

      - name: 6. Read current version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version

      - name: 6. Zip the build
        run:
          zip -r Select-Picture-in-Picture-${{steps.version.outputs.value}}.zip ./extension/
          
      - name: 7. Create release and upload release asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            Select-Picture-in-Picture-${{steps.version.outputs.value}}.zip
            LICENSE 