# This is a basic workflow to help you get started with Actions

name: Create release

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{matrix.node-version}}
          
      - name: 3. Cache dependencies
        uses: actions/cache@master
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}
          
      - name: 4. Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: 
          yarn install

      # Runs a set of commands using the runners shell
      - name: 5. Webpack build 
        run: |
          yarn build
      
